version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
    env_file:
      - ./.env
    ports:
      - 3000:3000
    networks:
      - frontend
networks:
  frontend:
