version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Adjust memory limits as needed
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - app
    healthcheck:
      test: ["CMD-SHELL", "curl -s --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - esdata:/usr/share/elasticsearch/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./.env
    ports:
      - 3000:3000
    networks:
      - app


  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend/src:/app/src
    env_file:
      - ./.env
    ports:
      - 5000:3000
    networks:
      - app
    depends_on:
      elasticsearch:
        condition: service_healthy


networks:
  app:

volumes:
  esdata:
