version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m" # Adjust memory limits as needed
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "curl -s --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - esdata:/usr/share/elasticsearch/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
    env_file:
      - ./.env
    ports:
      - 5000:3000
    networks:
      - backend
    depends_on:
      elasticsearch:
        condition: service_healthy
networks:
  backend:

volumes:
  esdata:
